spring:
  application:
    name: alarm-service
  profiles:
    default: local

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

naver:
  api:
    access-key: ${NAVER_ACCESS_KEY}
    secret-key: ${NAVER_SECRET_KEY}
    service-id: ${NAVER_SERVICE_ID}
    phone-number: 01091019320

aws:
    region: ap-northeast-2
    access-key-id: ${AWS_ACCESS_KEY_ID}
    secret-access-key: ${AWS_SECRET_ACCESS_KEY}
    sns:
      topic-arn: ${AWS_SNS_TOPIC_ARN}