server:
  port: 8080
  error:
    include-exception: true
    include-message: always
    include-stacktrace: never
    whitelabel:
      enabled: true
    path: /error

eureka:
  client:
    service-url:
      defaultZone: http://discovery.leekyusung.kr/eureka/
    register-with-eureka: true
    fetch-registry: true

springdoc:
  swagger-ui:
    path: /api-docs.html
    enabled: false
  api-docs:
    enabled: false

naver:
  api:
    access-key: ${NAVER_ACCESS_KEY}
    secret-key: ${NAVER_SECRET_KEY}
    service-id: ${NAVER_SERVICE_ID}
    phone-number: 01091019320